name: Npm package

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs 10.16.3
        uses: actions/setup-node@master
        with:
          version: 10.16.3

      - name: Build
        run: |
          npm ci
      - name: Test
        run: |
          npm test
